default_language_version:
  python: python3.7
repos:
  # Installed through poetry.
  - repo: local
    hooks:
    - id: seed-isort-config
      name: Seed isort with third-party libraries
      description: Statically populate the `known_third_party` `isort` setting.
      entry: seed-isort-config
      language: system
      types: [python]
      pass_filenames: false
      always_run: false
    - id: isort
      name: Sort imports (isort)
      description: Sort imports
      entry: isort
      language: system
      types: [python]
    - id: black
      name: Run code formatter (black)
      description: the uncompromising Python code formatter
      entry: black
      language: system
      types: [python]
    - id: flake8
      name: Run linter (flake8)
      description: linter and style guide enforcement
      entry: flake8
      language: system
      types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
